name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Environment Variables
        env:
          USER_ID: ${{ secrets.USER_ID }}
          SERVICE_ID: ${{ secrets.SERVICE_ID }}
          TEMPLATE_ID: ${{ secrets.TEMPLATE_ID }}
        run: |
          echo "window.ENV = {" > config.js
          echo "  USER_ID: '${USER_ID}'," >> config.js
          echo "  SERVICE_ID: '${SERVICE_ID}'," >> config.js
          echo "  TEMPLATE_ID: '${TEMPLATE_ID}'" >> config.js
          echo "};" >> config.js

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
          publish_branch: gh-pages
